### ISSUE TITLE
Jackson Databind version Exception on sonatypeBundleRelease

### ISSUE THREAD

**Issue by lolgab** [xerial/sbt-sonatype#171]
Hi :-) ,
I updates `sbt-sonatype` from `3.8.1` to `3.9.3` and I have this error on `sonatypeBundleRelease`.
My guess is that a different `jackson-*` I have somewhere in my project  (probably required by a `play-json` dependency) interferes with the one required by `sbt-sonatype`.

Here you find the Stacktrace:
```
[error] java.lang.ExceptionInInitializerError
[error]         at com.twitter.finagle.toggle.StandardToggleMap$.loadJsonConfigWithEnv(StandardToggleMap.scala:187)
[error]         at com.twitter.finagle.toggle.StandardToggleMap$.loadJsonConfig(StandardToggleMap.scala:127)
[error]         at com.twitter.finagle.toggle.StandardToggleMap$.apply(StandardToggleMap.scala:100)
[error]         at com.twitter.finagle.toggle.StandardToggleMap$.apply(StandardToggleMap.scala:85)
[error]         at com.twitter.finagle.http.package$.<init>(package.scala:18)
[error]         at com.twitter.finagle.http.package$.<clinit>(package.scala)
[error]         at com.twitter.finagle.Http$useH2$.<init>(Http.scala:47)
[error]         at com.twitter.finagle.Http$useH2$.<clinit>(Http.scala)
[error]         at com.twitter.finagle.Http$Client.newClient(Http.scala:342)
[error]         at com.twitter.finagle.client.EndpointerStackClient.newService(EndpointerStackClient.scala:148)
[error]         at com.twitter.finagle.client.EndpointerStackClient.newService$(EndpointerStackClient.scala:145)
[error]         at com.twitter.finagle.Http$Client.newService(Http.scala:168)
[error]         at com.twitter.finagle.Client.newService(Client.scala:43)
[error]         at com.twitter.finagle.Client.newService$(Client.scala:41)
[error]         at com.twitter.finagle.Http$Client.newService(Http.scala:168)
[error]         at wvlet.airframe.http.finagle.FinagleClient.<init>(FinagleClient.scala:122)
[error]         at wvlet.airframe.http.finagle.FinagleClient$.newSyncClient(FinagleClient.scala:357)
[error]         at wvlet.airframe.http.finagle.FinagleClientConfig.newSyncClient(FinagleClient.scala:97)
[error]         at xerial.sbt.sonatype.SonatypeClient.<init>(SonatypeClient.scala:81)
[error]         at xerial.sbt.Sonatype$.withSonatypeService(Sonatype.scala:396)
[error]         at xerial.sbt.Sonatype$.$anonfun$sonatypeBundleRelease$1(Sonatype.scala:154)
[error]         at sbt.Command$.$anonfun$command$2(Command.scala:96)
[error]         at sbt.Command$.process(Command.scala:187)
[error]         at sbt.MainLoop$.process$1(MainLoop.scala:199)
[error]         at sbt.MainLoop$.processCommand(MainLoop.scala:233)
[error]         at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:147)
[error]         at sbt.State$StateOpsImpl$.runCmd$1(State.scala:273)
[error]         at sbt.State$StateOpsImpl$.process$extension(State.scala:277)
[error]         at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:147)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.MainLoop$.next(MainLoop.scala:147)
[error]         at sbt.MainLoop$.run(MainLoop.scala:138)
[error]         at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:116)
[error]         at sbt.io.Using.apply(Using.scala:27)
[error]         at sbt.MainLoop$.runWithNewLog(MainLoop.scala:110)
[error]         at sbt.MainLoop$.runAndClearLast(MainLoop.scala:65)
[error]         at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:50)
[error]         at sbt.MainLoop$.runLogged(MainLoop.scala:41)
[error]         at sbt.StandardMain$.runManaged(Main.scala:132)
[error]         at sbt.xMain$.run(Main.scala:67)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:45)
[error]         at sbt.xMain.run(Main.scala:39)
[error]         at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
[error]         at xsbt.boot.Launch$.withContextLoader(Launch.scala:130)
[error]         at xsbt.boot.Launch$.run(Launch.scala:111)
[error]         at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
[error]         at xsbt.boot.Launch$.launch(Launch.scala:119)
[error]         at xsbt.boot.Launch$.apply(Launch.scala:20)
[error]         at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error]         at xsbt.boot.Boot$.main(Boot.scala:18)
[error]         at xsbt.boot.Boot.main(Boot.scala)
[error] Caused by: com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.9.10 requires Jackson Databind version >= 2.9.0 and < 2.10.0
[error]         at com.fasterxml.jackson.module.scala.JacksonModule.setupModule(JacksonModule.scala:61)
[error]         at com.fasterxml.jackson.module.scala.JacksonModule.setupModule$(JacksonModule.scala:46)
[error]         at com.fasterxml.jackson.module.scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:17)
[error]         at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:808)
[error]         at com.twitter.finagle.toggle.JsonToggleMap$.<init>(JsonToggleMap.scala:82)
[error]         at com.twitter.finagle.toggle.JsonToggleMap$.<clinit>(JsonToggleMap.scala)
[error]         at com.twitter.finagle.toggle.StandardToggleMap$.loadJsonConfigWithEnv(StandardToggleMap.scala:187)
[error]         at com.twitter.finagle.toggle.StandardToggleMap$.loadJsonConfig(StandardToggleMap.scala:127)
[error]         at com.twitter.finagle.toggle.StandardToggleMap$.apply(StandardToggleMap.scala:100)
[error]         at com.twitter.finagle.toggle.StandardToggleMap$.apply(StandardToggleMap.scala:85)
[error]         at com.twitter.finagle.http.package$.<init>(package.scala:18)
[error]         at com.twitter.finagle.http.package$.<clinit>(package.scala)
[error]         at com.twitter.finagle.Http$useH2$.<init>(Http.scala:47)
[error]         at com.twitter.finagle.Http$useH2$.<clinit>(Http.scala)
[error]         at com.twitter.finagle.Http$Client.newClient(Http.scala:342)
[error]         at com.twitter.finagle.client.EndpointerStackClient.newService(EndpointerStackClient.scala:148)
[error]         at com.twitter.finagle.client.EndpointerStackClient.newService$(EndpointerStackClient.scala:145)
[error]         at com.twitter.finagle.Http$Client.newService(Http.scala:168)
[error]         at com.twitter.finagle.Client.newService(Client.scala:43)
[error]         at com.twitter.finagle.Client.newService$(Client.scala:41)
[error]         at com.twitter.finagle.Http$Client.newService(Http.scala:168)
[error]         at wvlet.airframe.http.finagle.FinagleClient.<init>(FinagleClient.scala:122)
[error]         at wvlet.airframe.http.finagle.FinagleClient$.newSyncClient(FinagleClient.scala:357)
[error]         at wvlet.airframe.http.finagle.FinagleClientConfig.newSyncClient(FinagleClient.scala:97)
[error]         at xerial.sbt.sonatype.SonatypeClient.<init>(SonatypeClient.scala:81)
[error]         at xerial.sbt.Sonatype$.withSonatypeService(Sonatype.scala:396)
[error]         at xerial.sbt.Sonatype$.$anonfun$sonatypeBundleRelease$1(Sonatype.scala:154)
[error]         at sbt.Command$.$anonfun$command$2(Command.scala:96)
[error]         at sbt.Command$.process(Command.scala:187)
[error]         at sbt.MainLoop$.process$1(MainLoop.scala:199)
[error]         at sbt.MainLoop$.processCommand(MainLoop.scala:233)
[error]         at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:147)
[error]         at sbt.State$StateOpsImpl$.runCmd$1(State.scala:273)
[error]         at sbt.State$StateOpsImpl$.process$extension(State.scala:277)
[error]         at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:147)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.MainLoop$.next(MainLoop.scala:147)
[error]         at sbt.MainLoop$.run(MainLoop.scala:138)
[error]         at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:116)
[error]         at sbt.io.Using.apply(Using.scala:27)
[error]         at sbt.MainLoop$.runWithNewLog(MainLoop.scala:110)
[error]         at sbt.MainLoop$.runAndClearLast(MainLoop.scala:65)
[error]         at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:50)
[error]         at sbt.MainLoop$.runLogged(MainLoop.scala:41)
[error]         at sbt.StandardMain$.runManaged(Main.scala:132)
[error]         at sbt.xMain$.run(Main.scala:67)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:45)
[error]         at sbt.xMain.run(Main.scala:39)
[error]         at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
[error]         at xsbt.boot.Launch$.withContextLoader(Launch.scala:130)
[error]         at xsbt.boot.Launch$.run(Launch.scala:111)
[error]         at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
[error]         at xsbt.boot.Launch$.launch(Launch.scala:119)
[error]         at xsbt.boot.Launch$.apply(Launch.scala:20)
[error]         at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error]         at xsbt.boot.Boot$.main(Boot.scala:18)
[error]         at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.ExceptionInInitializerError
[error] Use 'last' for the full log.
```

Still I couldn't find a minimal reproduction of the problem.

**Comment by lolgab** [comment]
The problem is caused by [sbt-guardrail](https://github.com/twilio/sbt-guardrail).
I found a workaround which is to override the jackson-databind dependency right before publishing the bundle:
```bash
sbt "set dependencyOverrides += \"com.fasterxml.jackson.core\" % \"jackson-databind\" % \"2.9.10.1\" ; sonatypeBundleRelease"
```

**Comment by xerial** [comment]
ok. I'll try using an HTTP client which doesn't use any jackson dependency.

**Comment by lolgab** [comment]
In my particular case updating finagle in airframe solves the problem..
For any HTTP client you use there will be always problems when other plugins use different versions of the same dependency. So I think the problem is not solvable in general.

**Comment by xerial** [comment]
Just released sbt-sonatype 3.9.4, which has no dependency to Finagle and Jackson. I hope this fixes you issue. 
Using Finagle-based HTTP client was actually my concern for causing such an issue. Thanks for reporting.

**Comment by lolgab** [comment]
Thank you very much!
I tried locally and it seems to work! I'll tell you Monday when I will update production code :)

**Comment by lolgab** [comment]
I confirm version `3.9.4` works marvellously.
I'm closing the issue.
Thank you very much again :-)
