### ISSUE TITLE
Unexpected exceptions when reading staging repositories and profiles

### ISSUE THREAD

**Issue by plokhotnyuk** [xerial/sbt-sonatype#175]
```
2020-07-10 19:12:12.429+0200  info [SonatypeClient] Reading staging repository profiles...  - (SonatypeClient.scala:109)
java.io.IOException: Scala signature package has wrong version
 expected: 5.0
 found: 5.2 in scala.package
        at scala.reflect.internal.pickling.UnPickler$Scan.checkVersion(UnPickler.scala:124)
        at scala.reflect.internal.pickling.UnPickler$Scan.<init>(UnPickler.scala:66)
	at scala.reflect.internal.pickling.UnPickler.unpickle(UnPickler.scala:47)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.unpickleClass(JavaMirrors.scala:653)
	at scala.reflect.runtime.SymbolLoaders$TopClassCompleter.$anonfun$complete$2(SymbolLoaders.scala:37)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.reflect.internal.SymbolTable.slowButSafeEnteringPhaseNotLaterThan(SymbolTable.scala:332)
	at scala.reflect.runtime.SymbolLoaders$TopClassCompleter.complete(SymbolLoaders.scala:34)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1542)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$13.scala$reflect$runtime$SynchronizedSymbols$SynchronizedSymbol$$super$info(SynchronizedSymbols.scala:221)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.$anonfun$info$1(SynchronizedSymbols.scala:158)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.info(SynchronizedSymbols.scala:149)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.info$(SynchronizedSymbols.scala:158)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$13.info(SynchronizedSymbols.scala:221)
	at scala.reflect.internal.SymbolTable.openPackageModule(SymbolTable.scala:355)
	at scala.reflect.internal.SymbolTable.openPackageModule(SymbolTable.scala:410)
	at scala.reflect.runtime.SymbolLoaders$LazyPackageType.$anonfun$complete$3(SymbolLoaders.scala:83)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.reflect.internal.SymbolTable.slowButSafeEnteringPhaseNotLaterThan(SymbolTable.scala:332)
	at scala.reflect.runtime.SymbolLoaders$LazyPackageType.complete(SymbolLoaders.scala:80)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1542)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$9.scala$reflect$runtime$SynchronizedSymbols$SynchronizedSymbol$$super$info(SynchronizedSymbols.scala:209)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.$anonfun$info$1(SynchronizedSymbols.scala:158)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.info(SynchronizedSymbols.scala:149)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.info$(SynchronizedSymbols.scala:158)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$9.info(SynchronizedSymbols.scala:209)
	at scala.reflect.internal.Types$TypeRef.baseClasses(Types.scala:2278)
	at scala.reflect.internal.tpe.FindMembers$FindMemberBase.init(FindMembers.scala:36)
	at scala.reflect.internal.tpe.FindMembers$FindMember.init(FindMembers.scala:255)
	at scala.reflect.internal.Types$Type.$anonfun$findMember$1(Types.scala:1040)
	at scala.reflect.internal.Types$Type.findMemberInternal$1(Types.scala:1039)
	at scala.reflect.internal.Types$Type.findMember(Types.scala:1044)
	at scala.reflect.internal.Types$Type.memberBasedOnName(Types.scala:673)
	at scala.reflect.internal.Types$Type.member(Types.scala:637)
	at scala.reflect.internal.Mirrors$RootsBase.staticPackage(Mirrors.scala:59)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.staticPackage(JavaMirrors.scala:96)
	at scala.reflect.internal.Mirrors$RootsBase.$anonfun$init$1(Mirrors.scala:267)
	at scala.reflect.internal.Mirrors$RootsBase.init(Mirrors.scala:264)
	at scala.reflect.runtime.JavaMirrors.createMirror(JavaMirrors.scala:46)
	at scala.reflect.runtime.JavaMirrors.$anonfun$runtimeMirror$1(JavaMirrors.scala:63)
	at scala.reflect.runtime.JavaMirrors.runtimeMirror(JavaMirrors.scala:61)
	at scala.reflect.runtime.JavaMirrors.runtimeMirror$(JavaMirrors.scala:60)
	at scala.reflect.runtime.JavaUniverse.runtimeMirror(JavaUniverse.scala:30)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.mirrorDefining(JavaMirrors.scala:600)
	at scala.reflect.runtime.SymbolLoaders$PackageScope.$anonfun$lookupEntry$1(SymbolLoaders.scala:148)
	at scala.reflect.runtime.SymbolLoaders$PackageScope.syncLockSynchronized(SymbolLoaders.scala:133)
	at scala.reflect.runtime.SymbolLoaders$PackageScope.lookupEntry(SymbolLoaders.scala:135)
	at scala.reflect.internal.tpe.FindMembers$FindMemberBase.walkBaseClasses(FindMembers.scala:112)
	at scala.reflect.internal.tpe.FindMembers$FindMemberBase.searchConcreteThenDeferred(FindMembers.scala:80)
	at scala.reflect.internal.tpe.FindMembers$FindMemberBase.apply(FindMembers.scala:72)
	at scala.reflect.internal.Types$Type.$anonfun$findMember$1(Types.scala:1041)
	at scala.reflect.internal.Types$Type.findMemberInternal$1(Types.scala:1039)
	at scala.reflect.internal.Types$Type.findMember(Types.scala:1044)
	at scala.reflect.internal.Types$Type.memberBasedOnName(Types.scala:673)
	at scala.reflect.internal.Types$Type.member(Types.scala:637)
	at scala.reflect.internal.Types$Type.packageObject(Types.scala:649)
	at scala.reflect.internal.Symbols$Symbol.packageObject(Symbols.scala:868)
	at scala.reflect.internal.SymbolTable.openPackageModule(SymbolTable.scala:404)
	at scala.reflect.runtime.SymbolLoaders$LazyPackageType.$anonfun$complete$3(SymbolLoaders.scala:83)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.reflect.internal.SymbolTable.slowButSafeEnteringPhaseNotLaterThan(SymbolTable.scala:332)
	at scala.reflect.runtime.SymbolLoaders$LazyPackageType.complete(SymbolLoaders.scala:80)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1542)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$9.scala$reflect$runtime$SynchronizedSymbols$SynchronizedSymbol$$super$info(SynchronizedSymbols.scala:209)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.$anonfun$info$1(SynchronizedSymbols.scala:158)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.info(SynchronizedSymbols.scala:149)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.info$(SynchronizedSymbols.scala:158)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$9.info(SynchronizedSymbols.scala:209)
	at scala.reflect.internal.Types$TypeRef.baseClasses(Types.scala:2278)
	at scala.reflect.internal.tpe.FindMembers$FindMemberBase.init(FindMembers.scala:36)
	at scala.reflect.internal.tpe.FindMembers$FindMember.init(FindMembers.scala:255)
	at scala.reflect.internal.Types$Type.$anonfun$findMember$1(Types.scala:1040)
	at scala.reflect.internal.Types$Type.findMemberInternal$1(Types.scala:1039)
	at scala.reflect.internal.Types$Type.findMember(Types.scala:1044)
	at scala.reflect.internal.Types$Type.memberBasedOnName(Types.scala:673)
	at scala.reflect.internal.Types$Type.member(Types.scala:637)
	at scala.reflect.internal.Mirrors$RootsBase.staticPackage(Mirrors.scala:59)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.staticPackage(JavaMirrors.scala:96)
	at scala.reflect.internal.Mirrors$RootsBase.$anonfun$init$1(Mirrors.scala:267)
	at scala.reflect.internal.Mirrors$RootsBase.init(Mirrors.scala:264)
	at scala.reflect.runtime.JavaMirrors.createMirror(JavaMirrors.scala:46)
	at scala.reflect.runtime.JavaMirrors.$anonfun$runtimeMirror$1(JavaMirrors.scala:63)
	at scala.reflect.runtime.JavaMirrors.runtimeMirror(JavaMirrors.scala:61)
	at scala.reflect.runtime.JavaMirrors.runtimeMirror$(JavaMirrors.scala:60)
	at scala.reflect.runtime.JavaUniverse.runtimeMirror(JavaUniverse.scala:30)
	at scala.reflect.runtime.JavaUniverse.runtimeMirror(JavaUniverse.scala:30)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$.$anonfun$mirror$1(ReflectSurfaceFactory.scala:161)
	at scala.collection.concurrent.Map.getOrElseUpdate(Map.scala:97)
	at scala.collection.concurrent.Map.getOrElseUpdate$(Map.scala:94)
	at scala.collection.convert.Wrappers$JConcurrentMapWrapper.getOrElseUpdate(Wrappers.scala:333)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$.mirror(ReflectSurfaceFactory.scala:161)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$.wvlet$airframe$surface$reflect$ReflectSurfaceFactory$$resolveClass(ReflectSurfaceFactory.scala:167)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder.$anonfun$methodParametersOf$1(ReflectSurfaceFactory.scala:513)
	at scala.collection.immutable.List.map(List.scala:286)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder.methodParametersOf(ReflectSurfaceFactory.scala:513)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anon$1.apply(ReflectSurfaceFactory.scala:546)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anon$1.apply(ReflectSurfaceFactory.scala:539)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:127)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:126)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anon$1.applyOrElse(ReflectSurfaceFactory.scala:539)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$existentialTypeFactory$1.applyOrElse(ReflectSurfaceFactory.scala:533)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$existentialTypeFactory$1.applyOrElse(ReflectSurfaceFactory.scala:533)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$javaEnumFactory$1.applyOrElse(ReflectSurfaceFactory.scala:449)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$javaEnumFactory$1.applyOrElse(ReflectSurfaceFactory.scala:449)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$javaUtilFactory$1.applyOrElse(ReflectSurfaceFactory.scala:428)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$javaUtilFactory$1.applyOrElse(ReflectSurfaceFactory.scala:428)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$tupleFactory$1.applyOrElse(ReflectSurfaceFactory.scala:422)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$tupleFactory$1.applyOrElse(ReflectSurfaceFactory.scala:422)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$optionFactory$1.applyOrElse(ReflectSurfaceFactory.scala:417)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$optionFactory$1.applyOrElse(ReflectSurfaceFactory.scala:417)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$arrayFactory$1.applyOrElse(ReflectSurfaceFactory.scala:412)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$arrayFactory$1.applyOrElse(ReflectSurfaceFactory.scala:412)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$primitiveTypeFactory$1.applyOrElse(ReflectSurfaceFactory.scala:345)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$primitiveTypeFactory$1.applyOrElse(ReflectSurfaceFactory.scala:345)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$higherKindedTypeFactory$1.applyOrElse(ReflectSurfaceFactory.scala:372)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$higherKindedTypeFactory$1.applyOrElse(ReflectSurfaceFactory.scala:372)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$aliasFactory$1.applyOrElse(ReflectSurfaceFactory.scala:391)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$aliasFactory$1.applyOrElse(ReflectSurfaceFactory.scala:391)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$taggedTypeFactory$1.applyOrElse(ReflectSurfaceFactory.scala:386)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$taggedTypeFactory$1.applyOrElse(ReflectSurfaceFactory.scala:386)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder.surfaceOf(ReflectSurfaceFactory.scala:317)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$genericSurfaceFactory$1.$anonfun$applyOrElse$3(ReflectSurfaceFactory.scala:578)
	at scala.collection.immutable.List.map(List.scala:286)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$genericSurfaceFactory$1.applyOrElse(ReflectSurfaceFactory.scala:578)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$genericSurfaceFactory$1.applyOrElse(ReflectSurfaceFactory.scala:576)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:127)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:126)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anon$1.applyOrElse(ReflectSurfaceFactory.scala:539)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$existentialTypeFactory$1.applyOrElse(ReflectSurfaceFactory.scala:533)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$existentialTypeFactory$1.applyOrElse(ReflectSurfaceFactory.scala:533)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$javaEnumFactory$1.applyOrElse(ReflectSurfaceFactory.scala:449)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$javaEnumFactory$1.applyOrElse(ReflectSurfaceFactory.scala:449)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$javaUtilFactory$1.applyOrElse(ReflectSurfaceFactory.scala:428)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$javaUtilFactory$1.applyOrElse(ReflectSurfaceFactory.scala:428)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$tupleFactory$1.applyOrElse(ReflectSurfaceFactory.scala:422)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$tupleFactory$1.applyOrElse(ReflectSurfaceFactory.scala:422)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$optionFactory$1.applyOrElse(ReflectSurfaceFactory.scala:417)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$optionFactory$1.applyOrElse(ReflectSurfaceFactory.scala:417)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$arrayFactory$1.applyOrElse(ReflectSurfaceFactory.scala:412)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$arrayFactory$1.applyOrElse(ReflectSurfaceFactory.scala:412)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$primitiveTypeFactory$1.applyOrElse(ReflectSurfaceFactory.scala:345)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$primitiveTypeFactory$1.applyOrElse(ReflectSurfaceFactory.scala:345)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$higherKindedTypeFactory$1.applyOrElse(ReflectSurfaceFactory.scala:372)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$higherKindedTypeFactory$1.applyOrElse(ReflectSurfaceFactory.scala:372)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$aliasFactory$1.applyOrElse(ReflectSurfaceFactory.scala:391)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$aliasFactory$1.applyOrElse(ReflectSurfaceFactory.scala:391)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$taggedTypeFactory$1.applyOrElse(ReflectSurfaceFactory.scala:386)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder$$anonfun$taggedTypeFactory$1.applyOrElse(ReflectSurfaceFactory.scala:386)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$SurfaceFinder.surfaceOf(ReflectSurfaceFactory.scala:317)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$.$anonfun$apply$1(ReflectSurfaceFactory.scala:131)
	at scala.collection.concurrent.Map.getOrElseUpdate(Map.scala:97)
	at scala.collection.concurrent.Map.getOrElseUpdate$(Map.scala:94)
	at scala.collection.convert.Wrappers$JConcurrentMapWrapper.getOrElseUpdate(Wrappers.scala:333)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$.apply(ReflectSurfaceFactory.scala:131)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$.ofType(ReflectSurfaceFactory.scala:48)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$.localSurfaceOf(ReflectSurfaceFactory.scala:83)
	at wvlet.airframe.surface.SurfaceFactory$.localSurfaceOf(SurfaceFactory.scala:24)
	at wvlet.airframe.codec.MessageCodecFactory.of(MessageCodecFactory.scala:68)
	at xerial.sbt.sonatype.SonatypeService.withCache(SonatypeService.scala:123)
	at xerial.sbt.sonatype.SonatypeService.stagingProfiles(SonatypeService.scala:139)
	at xerial.sbt.sonatype.SonatypeService.currentProfile$lzycompute(SonatypeService.scala:144)
	at xerial.sbt.sonatype.SonatypeService.currentProfile(SonatypeService.scala:143)
	at xerial.sbt.sonatype.SonatypeService.createStage(SonatypeService.scala:155)
	at xerial.sbt.Sonatype$.$anonfun$prepare$3(Sonatype.scala:144)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2020-07-10 19:12:13.170+0200  info [SonatypeClient] Reading staging profiles...  - (SonatypeClient.scala:121)
2020-07-10 19:12:17.637+0200  warn [ObjectCodec] No factory is found for Map[String,Seq[StagingRepositoryProfile]]  - (ObjectCodec.scala:227)
2020-07-10 19:12:17.640+0200 error [Sonatype] 
java.lang.NullPointerException
	at xerial.sbt.sonatype.SonatypeClient.stagingRepositoryProfiles(SonatypeClient.scala:112)
	at xerial.sbt.sonatype.SonatypeService.stagingRepositoryProfiles(SonatypeService.scala:114)
	at xerial.sbt.sonatype.SonatypeService.findStagingRepositoryProfilesWithKey(SonatypeService.scala:108)
	at xerial.sbt.sonatype.SonatypeService.dropIfExistsByKey(SonatypeService.scala:95)
	at xerial.sbt.Sonatype$.$anonfun$prepare$2(Sonatype.scala:142)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)  - (Sonatype.scala:409)
```

**Comment by xerial** [comment]
Most likely this is an issue of Scala version incompatibility. Which version of sbt-sonatype is used and what version of Scala is used when running sbt?

**Comment by plokhotnyuk** [comment]
sbt 1.3.13
sbt-sonatype 3.9.4

The project has cross-built for Scala 2.11.12/2.12.11/2.13.3 and Scala.js 1.1.1: https://github.com/plokhotnyuk/jsoniter-scala

**Comment by plokhotnyuk** [comment]
All is fine from the second try.

Probably, it was some rare not properly handled error.

**Comment by xerial** [comment]
I saw this error when using the layered classloader of sbt 1.3.x. sbt-sonatype is using airframe-surface library to read JSON responses into Scala case classes by using reflection in order to see the case class parameters. The reported error can happen when sbt's classloader cannot find the target case class.
