### ISSUE TITLE
sbt-sonatype aborts during bundle release sometimes

### ISSUE THREAD

**Issue by exoego** [xerial/sbt-sonatype#181]
When I run `sbt clean +publishSigned sonatypeBundleRelease` for publishing my library, sbt-sonatype aborted with `java.io.IOException: Supplied file /home/vagrant/IdeaProjects/aws-lambda-scalajs-facade/target/sonatype-staging/0.10.0 is a not an existing directory!` error.
Fortunately, uploading to sonatype seems completed successfully, so I finished releasing manually .

Sorry in advance if the command `+publishSigned sonatypeBundleRelease` is not appropriate 🙏 

## My observation

This error tends to happen on my relatively-small libraries (containing a few sbt Projects of several hundreds line of codes).
However, it won't happen on my huge library (containing 200+ sbt Projects of thousands LoC).
So I am guessing `sonatypeBundleRelease` can not handle smaller libaries for some reason ...?

I also found that two "staging repository" are created.
In the below example, `exoego-1108` and `exoego-1109` are created at once on a single execution of `sbt clean +publishSigned sonatypeBundleRelease`.
Are these two stating repositories intended ?
I guess I am doing inappropriate with sbt-sonatype commands...
![Screenshot_2020-08-20](https://user-images.githubusercontent.com/127635/90701129-989a4000-e2c2-11ea-9c2e-f1a35c6ae338.png)

<details>
<summary>Log during releasing</summary>

```log
[info] welcome to sbt 1.3.13 (Ubuntu Java 11.0.8)
[info] loading settings for project aws-lambda-scalajs-facade-build from plugins.sbt ...
[info] loading project definition from /home/vagrant/IdeaProjects/aws-lambda-scalajs-facade/project
[info] loading settings for project aws-lambda-scalajs-facade from publishing.sbt,version.sbt,build.sbt ...
[info] set current project to aws-lambda-scalajs-facade (in build file:/home/vagrant/IdeaProjects/aws-lambda-scalajs-facade/)
[success] Total time: 1 s, completed 2020/08/20 8:43:07
[info] Setting Scala version to 2.12.12 on 1 projects.
[info] Reapplying settings...
[info] set current project to aws-lambda-scalajs-facade (in build file:/home/vagrant/IdeaProjects/aws-lambda-scalajs-facade/)
[info] Wrote /home/vagrant/IdeaProjects/aws-lambda-scalajs-facade/target/scala-2.12/aws-lambda-scalajs-facade_sjs1_2.12-0.10.0.pom
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Main Scala API documentation to /home/vagrant/IdeaProjects/aws-lambda-scalajs-facade/target/scala-2.12/api...
[info] Compiling 30 Scala sources to /home/vagrant/IdeaProjects/aws-lambda-scalajs-facade/target/scala-2.12/classes ...
model contains 365 documentable templates
[info] Done compiling.
[info] Main Scala API documentation successful.
[info] 	published aws-lambda-scalajs-facade_sjs1_2.12 to https://oss.sonatype.org/service/local/staging/deploy/maven2/net/exoego/aws-lambda-scalajs-facade_sjs1_2.12/0.10.0/aws-lambda-scalajs-facade_sjs1_2.12-0.10.0.pom
[info] 	published aws-lambda-scalajs-facade_sjs1_2.12 to https://oss.sonatype.org/service/local/staging/deploy/maven2/net/exoego/aws-lambda-scalajs-facade_sjs1_2.12/0.10.0/aws-lambda-scalajs-facade_sjs1_2.12-0.10.0.pom.asc
[info] 	published aws-lambda-scalajs-facade_sjs1_2.12 to https://oss.sonatype.org/service/local/staging/deploy/maven2/net/exoego/aws-lambda-scalajs-facade_sjs1_2.12/0.10.0/aws-lambda-scalajs-facade_sjs1_2.12-0.10.0-javadoc.jar.asc
[info] 	published aws-lambda-scalajs-facade_sjs1_2.12 to https://oss.sonatype.org/service/local/staging/deploy/maven2/net/exoego/aws-lambda-scalajs-facade_sjs1_2.12/0.10.0/aws-lambda-scalajs-facade_sjs1_2.12-0.10.0.jar
[info] 	published aws-lambda-scalajs-facade_sjs1_2.12 to https://oss.sonatype.org/service/local/staging/deploy/maven2/net/exoego/aws-lambda-scalajs-facade_sjs1_2.12/0.10.0/aws-lambda-scalajs-facade_sjs1_2.12-0.10.0-javadoc.jar
[info] 	published aws-lambda-scalajs-facade_sjs1_2.12 to https://oss.sonatype.org/service/local/staging/deploy/maven2/net/exoego/aws-lambda-scalajs-facade_sjs1_2.12/0.10.0/aws-lambda-scalajs-facade_sjs1_2.12-0.10.0.jar.asc
[info] 	published aws-lambda-scalajs-facade_sjs1_2.12 to https://oss.sonatype.org/service/local/staging/deploy/maven2/net/exoego/aws-lambda-scalajs-facade_sjs1_2.12/0.10.0/aws-lambda-scalajs-facade_sjs1_2.12-0.10.0-sources.jar
[info] 	published aws-lambda-scalajs-facade_sjs1_2.12 to https://oss.sonatype.org/service/local/staging/deploy/maven2/net/exoego/aws-lambda-scalajs-facade_sjs1_2.12/0.10.0/aws-lambda-scalajs-facade_sjs1_2.12-0.10.0-sources.jar.asc
[success] Total time: 44 s, completed 2020/08/20 8:43:52
[info] Setting Scala version to 2.13.3 on 1 projects.
[info] Reapplying settings...
[info] set current project to aws-lambda-scalajs-facade (in build file:/home/vagrant/IdeaProjects/aws-lambda-scalajs-facade/)
[info] Wrote /home/vagrant/IdeaProjects/aws-lambda-scalajs-facade/target/scala-2.13/aws-lambda-scalajs-facade_sjs1_2.13-0.10.0.pom
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Main Scala API documentation to /home/vagrant/IdeaProjects/aws-lambda-scalajs-facade/target/scala-2.13/api...
[info] Compiling 30 Scala sources to /home/vagrant/IdeaProjects/aws-lambda-scalajs-facade/target/scala-2.13/classes ...
[info] Done compiling.
[info] Main Scala API documentation successful.
[info] 	published aws-lambda-scalajs-facade_sjs1_2.13 to https://oss.sonatype.org/service/local/staging/deploy/maven2/net/exoego/aws-lambda-scalajs-facade_sjs1_2.13/0.10.0/aws-lambda-scalajs-facade_sjs1_2.13-0.10.0.pom
[info] 	published aws-lambda-scalajs-facade_sjs1_2.13 to https://oss.sonatype.org/service/local/staging/deploy/maven2/net/exoego/aws-lambda-scalajs-facade_sjs1_2.13/0.10.0/aws-lambda-scalajs-facade_sjs1_2.13-0.10.0.pom.asc
[info] 	published aws-lambda-scalajs-facade_sjs1_2.13 to https://oss.sonatype.org/service/local/staging/deploy/maven2/net/exoego/aws-lambda-scalajs-facade_sjs1_2.13/0.10.0/aws-lambda-scalajs-facade_sjs1_2.13-0.10.0-javadoc.jar.asc
[info] 	published aws-lambda-scalajs-facade_sjs1_2.13 to https://oss.sonatype.org/service/local/staging/deploy/maven2/net/exoego/aws-lambda-scalajs-facade_sjs1_2.13/0.10.0/aws-lambda-scalajs-facade_sjs1_2.13-0.10.0.jar
[info] 	published aws-lambda-scalajs-facade_sjs1_2.13 to https://oss.sonatype.org/service/local/staging/deploy/maven2/net/exoego/aws-lambda-scalajs-facade_sjs1_2.13/0.10.0/aws-lambda-scalajs-facade_sjs1_2.13-0.10.0-javadoc.jar
[info] 	published aws-lambda-scalajs-facade_sjs1_2.13 to https://oss.sonatype.org/service/local/staging/deploy/maven2/net/exoego/aws-lambda-scalajs-facade_sjs1_2.13/0.10.0/aws-lambda-scalajs-facade_sjs1_2.13-0.10.0.jar.asc
[info] 	published aws-lambda-scalajs-facade_sjs1_2.13 to https://oss.sonatype.org/service/local/staging/deploy/maven2/net/exoego/aws-lambda-scalajs-facade_sjs1_2.13/0.10.0/aws-lambda-scalajs-facade_sjs1_2.13-0.10.0-sources.jar
[info] 	published aws-lambda-scalajs-facade_sjs1_2.13 to https://oss.sonatype.org/service/local/staging/deploy/maven2/net/exoego/aws-lambda-scalajs-facade_sjs1_2.13/0.10.0/aws-lambda-scalajs-facade_sjs1_2.13-0.10.0-sources.jar.asc
[success] Total time: 24 s, completed 2020/08/20 q8:44:16
[info] Reapplying settings...
[info] set current project to aws-lambda-scalajs-facade (in build file:/home/vagrant/IdeaProjects/aws-lambda-scalajs-facade/)
[info] Preparing a new staging repository for [sbt-sonatype] aws-lambda-scalajs-facade 0.10.0
2020-08-20 08:44:16.235+0900  info [SonatypeService] sonatypeRepository  : https://oss.sonatype.org/service/local  - (SonatypeService.scala:24)
2020-08-20 08:44:16.237+0900  info [SonatypeService] sonatypeProfileName : net.exoego  - (SonatypeService.scala:25)
2020-08-20 08:44:16.238+0900  info [SonatypeClient] Reading staging repository profiles...  - (SonatypeClient.scala:109)
2020-08-20 08:44:16.901+0900  info [SonatypeClient] Reading staging profiles...  - (SonatypeClient.scala:121)
2020-08-20 08:44:17.754+0900  info [SonatypeService] No previous staging repository for [sbt-sonatype] aws-lambda-scalajs-facade 0.10.0 was found  - (SonatypeService.scala:97)
2020-08-20 08:44:19.836+0900  info [SonatypeClient] Creating a staging repository in profile net.exoego with a description key: [sbt-sonatype] aws-lambda-scalajs-facade 0.10.0  - (SonatypeClient.scala:127)
2020-08-20 08:44:29.439+0900  info [SonatypeClient] Created successfully: netexoego-1109  - (SonatypeClient.scala:140)
2020-08-20 08:44:29.448+0900 error [Sonatype]
java.io.IOException: Supplied file /home/vagrant/IdeaProjects/aws-lambda-scalajs-facade/target/sonatype-staging/0.10.0 is a not an existing directory!
	at org.sonatype.spice.zapper.fs.AbstractDirectory.<init>(AbstractDirectory.java:32)
	at org.sonatype.spice.zapper.fs.DirectoryIOSource.<init>(DirectoryIOSource.java:68)
	at org.sonatype.spice.zapper.fs.DirectoryIOSource.<init>(DirectoryIOSource.java:59)
	at org.sonatype.spice.zapper.fs.DirectoryIOSource.<init>(DirectoryIOSource.java:50)
	at xerial.sbt.sonatype.SonatypeClient.$anonfun$uploadBundle$1(SonatypeClient.scala:286)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at wvlet.airframe.control.Retry$RetryContext.runInternal(Retry.scala:265)
	at wvlet.airframe.control.Retry$RetryContext.run(Retry.scala:253)
	at xerial.sbt.sonatype.SonatypeClient.uploadBundle(SonatypeClient.scala:271)
	at xerial.sbt.sonatype.SonatypeService.uploadBundle(SonatypeService.scala:71)
	at xerial.sbt.Sonatype$.$anonfun$sonatypeBundleRelease$2(Sonatype.scala:158)
	at xerial.sbt.Sonatype$.withSonatypeService(Sonatype.scala:403)
	at xerial.sbt.Sonatype$.$anonfun$sonatypeBundleRelease$1(Sonatype.scala:154)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:130)
	at xsbt.boot.Launch$.run(Launch.scala:111)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
	at xsbt.boot.Launch$.launch(Launch.scala:119)
	at xsbt.boot.Launch$.apply(Launch.scala:20)
	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
	at xsbt.boot.Boot$.main(Boot.scala:18)  - (Sonatype.scala:409)
```
</details>

## My environment

* JDK 11.0.8
* Scala 2.13.3 & 2.12.12
* sbt 1.3.13
* sbt-sonatype 3.9.4
* sbt-pgp 2.0.1

**Comment by xerial** [comment]
Having `implicitly created (auto staging)` staging repository on Sonatype is unexpected behavior. This is often created when sbt publishes artifacts to Sonatype without starting any session without using sbt-sonatype.

The local bundle folder needs to be the same folder for all cross-build projects. Check your `sonatypeBundleDirectory` setting. This value needs to be the same for all of the cross-build modules.

If some values are different, you can also manually specify the bundle directory like this:
```scala
sonatypeBundleDirectory := (ThisBuild / baseDirectory).value / target.value.getName / "sonatype-staging" / s"${version.value}"
````

**Comment by xerial** [comment]
Another possibility is your `publishTo` setting might not be pointing to the local folder (specified by sonatypeBundleDirecotry). Make sure all of your crossbuild projects properly have this setting:
```
publishTo := sonatypePublishToBundle.value
```

**Comment by xerial** [comment]
For example, you can force using the same publishTo setting in your build globally like this:
```scala
publishTo in ThisBuild := sonatypePublishToBundle.value
```
