### ISSUE TITLE
Supplied file is a not an existing directory!

### ISSUE THREAD

**Issue by tomasherman** [xerial/sbt-sonatype#268]
Hello, for some reason my builds started failing with following error:
```
[info] 	published datadog4s-jvm_3 to https://oss.sonatype.org/content/repositories/snapshots/com/avast/cloud/datadog4s-jvm_3/0.31.1+0-0b2566ae+20211209-1518-SNAPSHOT/datadog4s-jvm_3-0.31.1+0-0b2566ae+20211209-1518-SNAPSHOT-javadoc.jar.asc
[info] 	published datadog4s-jvm_3 to https://oss.sonatype.org/content/repositories/snapshots/com/avast/cloud/datadog4s-jvm_3/0.31.1+0-0b2566ae+20211209-1518-SNAPSHOT/datadog4s-jvm_3-0.31.1+0-0b2566ae+20211209-1518-SNAPSHOT-sources.jar.asc
[info] 	published datadog4s-jvm_3 to https://oss.sonatype.org/content/repositories/snapshots/com/avast/cloud/datadog4s-jvm_3/0.31.1+0-0b2566ae+20211209-1518-SNAPSHOT/datadog4s-jvm_3-0.31.1+0-0b2566ae+20211209-1518-SNAPSHOT.jar.asc
[success] Total time: 34 s, completed Dec 9, 2021 3:19:24 PM
[info] Reapplying settings...
[info] set current project to datadog4s (in build file:/home/runner/work/datadog4s/datadog4s/)
2021-12-09 15:19:25.432Z  info [SonatypeService] sonatypeRepository  : https://oss.sonatype.org/service/local  - (SonatypeService.scala:26)
2021-12-09 15:19:25.437Z  info [SonatypeService] sonatypeProfileName : com.avast  - (SonatypeService.scala:27)
[info] Preparing a new staging repository for [sbt-sonatype] datadog4s 0.31.1+0-0b2566ae+20211209-1519-SNAPSHOT
2021-12-09 15:19:25.438Z  info [SonatypeClient] Reading staging repository profiles...  - (SonatypeClient.scala:108)
2021-12-09 15:19:26.922Z  info [SonatypeClient] Reading staging profiles...  - (SonatypeClient.scala:120)
2021-12-09 15:19:27.350Z  info [SonatypeService] No previous staging repository for [sbt-sonatype] datadog4s 0.31.1+0-0b2566ae+20211209-1519-SNAPSHOT was found  - (SonatypeService.scala:99)
2021-12-09 15:19:28.679Z  info [SonatypeClient] Creating a staging repository in profile com.avast with a description key: [sbt-sonatype] datadog4s 0.31.1+0-0b2566ae+20211209-1519-SNAPSHOT  - (SonatypeClient.scala:126)
2021-12-09 15:19:44.547Z  info [SonatypeClient] Created successfully: comavast-1318  - (SonatypeClient.scala:139)
2021-12-09 15:19:44.568Z error [Sonatype] 
java.io.IOException: Supplied file /home/runner/work/datadog4s/datadog4s/target/sonatype-staging/0.31.1+0-0b2566ae+20211209-1519-SNAPSHOT is a not an existing directory!
	at org.sonatype.spice.zapper.fs.AbstractDirectory.<init>(AbstractDirectory.java:32)
	at org.sonatype.spice.zapper.fs.DirectoryIOSource.<init>(DirectoryIOSource.java:68)
	at org.sonatype.spice.zapper.fs.DirectoryIOSource.<init>(DirectoryIOSource.java:59)
```
As you can see, some snapshots are published, but then for some reason a new staging repository gets created and it's name doesn't really match the name of the artifacts:

- snapshot is published with `datadog4s-jvm_3-0.31.1+0-0b2566ae+20211209-1518` in name
- repository that's created has name: `datadog4s 0.31.1+0-0b2566ae+20211209-1519`
Increase of 151`8` -> 151`9`

I don't really understand sonatype but the publishing worked fine for more than a year, now i wanted to do a maintenance release with dependency updates (including sbt-ci-release bumps) and it's not working anymore. Do you have any idea what might be going on?

Thank you!

**Comment by jbwheatley** [comment]
@tomasherman did you find a solution to this?

**Comment by tomasherman** [comment]
Hi, yes: https://github.com/sbt/sbt-ci-release/issues/216

**Comment by michaelmior** [comment]
@tomasherman Could you clarify what the solution is? I'm hitting this error also even when I completely remove the sbt-ci-release plugin.
