### ISSUE TITLE
sonatypeRelease fails

### ISSUE THREAD

**Issue by newhoggy** [xerial/sbt-sonatype#38]
```
$ sbt +publishSigned
.... succeeds ....
```

I can see my published artifacts in the staging repository:

![image](https://cloud.githubusercontent.com/assets/63014/23043138/6d057a1e-f4ef-11e6-937c-e226a1a69505.png)

```
$ sbt +sonatypeRelease
[info] Loading project definition from /Users/jky/wrk/personal/pico-hashids/project
[info] Set current project to pico-hashids (in build file:/Users/jky/wrk/personal/pico-hashids/)
[info] Setting version to 2.10.6
[info] Reapplying settings...
[info] Set current project to pico-hashids (in build file:/Users/jky/wrk/personal/pico-hashids/)
[info] Nexus repository URL: https://oss.sonatype.org/service/local
[info] sonatypeProfileName = org.picoworks
[info] Reading staging repository profiles...
[warn] No staging repository is found. Do publishSigned first.
java.lang.IllegalStateException: No staging repository is found. Run publishSigned first
	at xerial.sbt.Sonatype$NexusRESTService.findTargetRepository(Sonatype.scala:461)
	at xerial.sbt.Sonatype$SonatypeCommand$$anonfun$19.apply(Sonatype.scala:205)
	at xerial.sbt.Sonatype$SonatypeCommand$$anonfun$19.apply(Sonatype.scala:198)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:96)
	at sbt.MainLoop$.run(MainLoop.scala:89)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
	at sbt.StandardMain$.runManaged(Main.scala:57)
	at sbt.xMain.run(Main.scala:29)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.IllegalStateException: No staging repository is found. Run publishSigned first
[error] Use 'last' for the full log.
```

**Comment by xerial** [comment]
Check your `sonatypeProfile` setting (This is the same value with `organization` in default).

`central bundle` is not the right place for the target of publishSigned and sonatypeRelease.
