### ISSUE TITLE
Occasional SAXParseException

### ISSUE THREAD

**Issue by Atry** [xerial/sbt-sonatype#81]
sbt-sonatype occasionally throws a `SAXParseException`:

```
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512M; support was removed in 8.0
[info] Loading settings for project binding-scala-build-build from plugins.sbt ...
[info] Loading project definition from /home/travis/build/ThoughtWorksInc/Binding.scala/project/project
[info] Loading settings for project binding-scala-build from coursier.sbt,plugins.sbt ...
[info] Loading project definition from /home/travis/build/ThoughtWorksInc/Binding.scala/project
[info] Loading settings for project fxmlJVM from build.sbt ...
[info] Loading settings for project fxmlJS from build.sbt ...
[info] Loading settings for project XmlExtractorJVM from build.sbt ...
[info] Loading settings for project XmlExtractorJS from build.sbt ...
[info] Loading settings for project FutureBindingJVM from build.sbt ...
[info] Loading settings for project FutureBindingJS from build.sbt ...
[info] Loading settings for project BindingJVM from build.sbt ...
[info] Loading settings for project BindingJS from build.sbt ...
[info] Loading settings for project SafeBufferJVM from build.sbt ...
[info] Loading settings for project SafeBufferJS from build.sbt ...
[info] Loading settings for project JsPromiseBinding from build.sbt ...
[info] Loading settings for project Route from build.sbt ...
[info] Loading settings for project dom from build.sbt ...
[info] Loading settings for project secret from secret.sbt ...
[info] Loading settings for project binding-scala from build.sbt,dynver-dash-separator.sbt,secret.sbt ...
[info] Resolving key references (10173 settings) ...
[info] Set current project to binding-scala (in build file:/home/travis/build/ThoughtWorksInc/Binding.scala/)
[info] Setting Scala version to 2.11.12 on 14 projects.
[info] Excluded 1 projects, run ++ 2.11.12 -v for more details.
[info] Reapplying settings...
[info] Set current project to binding-scala (in build file:/home/travis/build/ThoughtWorksInc/Binding.scala/)
[info] Nexus repository URL: https://oss.sonatype.org/service/local
[info] sonatypeProfileName = com.thoughtworks.binding
[info] Reading staging profiles...
[info] Creating staging repository in profile: com.thoughtworks.binding
[error] org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 3; The element type "hr" must be terminated by the matching end-tag "</hr>".
[error] 	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
[error] 	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
[error] 	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
[error] 	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
[error] 	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
[error] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1749)
[error] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
[error] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
[error] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
[error] 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
[error] 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
[error] 	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
[error] 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
[error] 	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
[error] 	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
[error] 	at scala.xml.factory.XMLLoader.loadXML(XMLLoader.scala:41)
[error] 	at scala.xml.factory.XMLLoader.loadXML$(XMLLoader.scala:37)
[error] 	at scala.xml.XML$.loadXML(XML.scala:60)
[error] 	at scala.xml.factory.XMLLoader.load(XMLLoader.scala:53)
[error] 	at scala.xml.factory.XMLLoader.load$(XMLLoader.scala:53)
[error] 	at scala.xml.XML$.load(XML.scala:60)
[error] 	at xerial.sbt.Sonatype$NexusRESTService.$anonfun$createStage$2(Sonatype.scala:727)
[error] 	at xerial.sbt.Sonatype$NexusRESTService.$anonfun$createStage$2$adapted(Sonatype.scala:726)
[error] 	at xerial.sbt.Sonatype$NexusRESTService.$anonfun$Post$1(Sonatype.scala:612)
[error] 	at xerial.sbt.Sonatype$NexusRESTService.$anonfun$Post$1$adapted(Sonatype.scala:603)
[error] 	at xerial.sbt.Sonatype$NexusRESTService.withHttpClient(Sonatype.scala:637)
[error] 	at xerial.sbt.Sonatype$NexusRESTService.Post(Sonatype.scala:603)
[error] 	at xerial.sbt.Sonatype$NexusRESTService.createStage(Sonatype.scala:726)
[error] 	at xerial.sbt.Sonatype$SonatypeCommand$.$anonfun$sonatypeOpen$1(Sonatype.scala:216)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:142)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
[error] 	at sbt.Command$.process(Command.scala:181)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:151)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:246)
[error] 	at sbt.State$$anon$1.process(State.scala:250)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:139)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:132)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:138)
[error] 	at sbt.xMain.run(Main.scala:89)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 3; The element type "hr" must be terminated by the matching end-tag "</hr>".
[error] Use 'last' for the full log.
```

https://travis-ci.org/ThoughtWorksInc/Binding.scala/jobs/512904034

**Comment by xerial** [comment]
It looks like Sonatype is returning HTML response, instead of XML.. Weird...

**Comment by Atry** [comment]
I guess there may be an error HTTP status

**Comment by xerial** [comment]
https://github.com/xerial/sbt-sonatype/blob/465d4688944de884b612396ec199cdb9b6518138/src/main/scala/xerial/sbt/Sonatype.scala#L575

HTTP status code (200) is checked here, so after that XML (or html) will be parsed.

**Comment by Atry** [comment]
This bug report is a POST request.

It seems that only 500 error status is checked for POST status.
https://github.com/xerial/sbt-sonatype/blob/465d4688944de884b612396ec199cdb9b6518138/src/main/scala/xerial/sbt/Sonatype.scala#L609

**Comment by xerial** [comment]
Nice catch! Then we need to have more proper status code handling here.

**Comment by regiskuckaertz** [comment]
hi - have been hit by the same issue, using sbt-sonatype 3.8. is there a temporary workaround? this is blocking some important release on our side.

**Comment by xerial** [comment]
Right. Sonatype sometimes returns HTML responses for XML request. 

I'm thinking about switching to JSON based APIs and adding more retries around the parsing errors.

**Comment by regiskuckaertz** [comment]
imo Sonatype should fix this, you do everything right. I've been trying to publish an artefact for 6 hours and it's failing all the time 🤦‍♂

**Comment by hubertp** [comment]
Judging from Sonatype's issue tracker (https://issues.sonatype.org/projects/OSSRH/issues/OSSRH-52239?filter=allopenissues)  I would say that this SAXParserException is just because we are getting socket timeouts in a form of automatic HTML failure responses. the plugin should probably still recognize it and print a more informative error message.

**Comment by xerial** [comment]
ok. I'll work on handling XML parsing exceptions

**Comment by mpollmeier** [comment]
thank you! at the moment, all of our travis-ci.org builds are affected. 
unfortunately changing the plugin probably won't fix it, but being able to see the error response from sonatype would help tremendously. let me know if i can help in any way.

**Comment by djspiewak** [comment]
I hate to be a "me too", but I'm now getting this constantly and cannot publish. :-(

**Comment by mpollmeier** [comment]
situation with sonatype seems to improve, some builds have gone through recently.

**Comment by xerial** [comment]
Actually if sonatype API is down for such a long time (almost 2 days...), even if we add backoff retries, it will not solve this.

**Comment by mpollmeier** [comment]
That's true, but being able to see the error response from sonatype would help tremendously.

**Comment by xerial** [comment]
sbt-sonatype 3.9.1 has switched to JSON based API, so this error will no longer happen. Thanks.

**Comment by xerial** [comment]
I also introduced different timeout settings for creating a new stage (up to 5 min as this needs to be a single HTTP request) and for closing and promoting stages (up to 60 min). I hope this will mitigate this type of slow response issues.

**Comment by regiskuckaertz** [comment]
Brilliant 👍

**Comment by xerial** [comment]
@mpollmeier Another improvement is that the latest version shows the error response in the warning log even if it is an HTML response :)

**Comment by mpollmeier** [comment]
yay thank you! :bowing_man:
